[package]
name = "uefi_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
goblin = { version = "0.9.3", features = ["elf64"] }
log = "0.4.27"
uefi = { version = "0.35.0", features = ["logger", "panic_handler"] }
